language: python
python:
    - "3.6"
before_install:
 - sudo apt-get update
 - sudo apt-get install -qq python-numpy python-scipy
# command to install dependencies
install: "pip install -r requirements-dev.txt"
# command to run tests
script: pytest
script: cd doc && make html
after_success:
  - ./push_to_pages.sh
