name: bdranalytics
# This environment is designed to work WITH the bdranalytics module: it includes the module including its dependencies
dependencies:
- python=3.6
- cmake
- boost
- tensorflow
- keras
- pkgconfig
- jupyter
- conda-forge::xgboost=0.6a2
- pip
- pip:
  - -rrequirements.txt
