name: bdranalytics
# This environment is designed to work WITH the bdranalytics module: it includes the module including its dependencies
dependencies:
- python=2.7
- cmake
- boost
- pkgconfig
- jupyter
- tensorflow
- conda-forge::xgboost=0.6a2
- pip
- pip:
  - -rrequirements.txt
