name: bdranalytics
dependencies:
- python=2.7
- NumPy>=1.6.1
- SciPy>=0.9
- scikit-learn>=0.18
- pytest
- jupyter
- matplotlib
- pandas
- statsmodels
- pip
- pip:
  - pytest-runner
  - -rrequirements.txt
