name: bdranalytics-dev
# This environment is designed to work ON the bdranalytics module: it includes its dependencies, but not bdranalytics itself.
dependencies:
- python=3.6
- cmake
- boost
- pkgconfig
- jupyter
- tensorflow
- conda-forge::xgboost=0.6a2
- pip
- pip:
  - -rrequirements-dev.txt
